yungyuc/nsdhw_21au

hw1/Luke2336/countline.py, hw1/Luke2336/countline.sh
=> [hw1] Luke2336 2nd attempt

hw1/hsjts0u/countline.py, hw1/hsjts0u/countline.sh
=> hsjts0u hw1 attempt1 branch fix

hw1/Cycatz-nycu/countline.py, hw1/Cycatz-nycu/countline.sh
=>  Submit Cycatz-nycu's hw1 files 

hw1/hcgcarry/countline.py, hw1/hcgcarry/countline.sh
=> [hw1] hcgcarry attempt 2 

hw1/sam29309010/countline.py, hw1/sam29309010/countline.sh
=> sam29309010 HW1 2nd attempt

hw1/secondlevel/countline.py, hw1/secondlevel/countline.sh
=> Secondlevel hw1 attempt2

hw1/secondlevel/countline.py, hw1/secondlevel/countline.sh
=> Secondlevel hw1 attempt1

hw1/LittleLaGi/countline.py, hw1/LittleLaGi/countline.sh
=> LittleLaGi hw1 attempt1

hw1/chrisPyr/countline.py, hw1/chrisPyr/countline.sh
=> [HW1]  chrisPyr 2nd attempt

hw1/BoWeii/countline.py, hw1/BoWeii/countline.sh
=> BoWeii-hw1-attemp2

hw1/abt8601/countline.py, hw1/abt8601/countline.sh
=> abt8601 HW1 Attempt 1

hw1/ran-ablaze/countline.py, hw1/ran-ablaze/countline.sh
=> [HW1] rab-ablaze's 2nd attempt

hw1/Hydr8O/countline.py, hw1/Hydr8O/countline.sh
=> second try

hw1/B106Roger/countline.py, hw1/B106Roger/countline.sh
---
- [v] A clear title
- [v] A meaningful message for PR, as well as its commits
- [v] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [v] excluding any irrelevant files, such as binaries, text files, or dot files
- [v] passing tests/CI
=> [HW1] 1st attempt

hw0/README.rst, hw1/wwweiwei/countline.py, hw1/wwweiwei/countline.sh
=> wwweiwei hw1 attempt1

hw1/mylin0405/countline.py, hw1/mylin0405/countline.sh
=> [HW1] mylin0405 2nd-attempt 

hw1/psychicalcoder/countline.py, hw1/psychicalcoder/countline.sh
=> [HW1] psychicalcoder's first attempt

hw1/nctu16028/countline.py, hw1/nctu16028/countline.sh
=> nctu16028's first attempt for hw1

hw1/jyunkaichen/countline.py, hw1/jyunkaichen/countline.sh
=> [HW1] jyunkaichen attempt1

hw1/crystal0523/countline.py, hw1/crystal0523/countline.sh
=> crystal0523-hw1-attempt4

hw1/Yuan-Hsuan/countline.py, hw1/Yuan-Hsuan/countline.sh
=> [hw1] Yuan hsuan 1st attempt

hw1/anva-kn/countline.py, hw1/anva-kn/countline.sh
---
This PR is for the first attempt on HW1 submission. Added two files: countline.sh for the first question and modified countline.py for the second question
=> anva-kn Attempt 1 for HW1

hw1/S413/countline.py, hw1/S413/countline.sh
=> S413-HW1-Attempt2

hw1/whtang906/countline.py, hw1/whtang906/countline.sh
=> [HW1] whtang906 attempt1

hw1/aiiuii/countline.py, hw1/aiiuii/countline.sh
=> aiiuii hw1 attempt1

hw1/aa940249tw/countline.py, hw1/aa940249tw/countline.sh
=> aa940249tw-hw1-attempt1

hw1/franktseng0718/countline.py, hw1/franktseng0718/countline.sh
=> first attempt

hw1/franktseng0718/countline.py, hw1/franktseng0718/countline.sh
=> franktseng0718-hw1-attempt2

hw2/abt8601/.gitignore, hw2/abt8601/q1/Makefile, hw2/abt8601/q1/line.cpp, hw2/abt8601/q1/line.hpp, hw2/abt8601/q1/main.cpp, hw2/abt8601/q2/Makefile, hw2/abt8601/q2/test_vector.py, hw2/abt8601/q2/vector.cpp, hw2/abt8601/q2/vector.hpp, hw2/abt8601/q2/vector_pybind.cpp
=> abt8601 HW2 Attempt 1

hw2/anva-kn/q1/Makefile, hw2/anva-kn/q1/line.cpp, hw2/anva-kn/q1/line.hpp, hw2/anva-kn/q1/main.cpp, hw2/anva-kn/q2/Makefile, hw2/anva-kn/q2/_vector.cpp, hw2/anva-kn/q2/test_vector.py
---
This PR includes hw2 files. Repositories were created according to guiidelines.
=> anva-kn hw2 attempt 1

hw2/hsjts0u/q1/Line.cpp, hw2/hsjts0u/q1/Line.hpp, hw2/hsjts0u/q1/Makefile, hw2/hsjts0u/q1/main.cpp, hw2/hsjts0u/q2/Makefile, hw2/hsjts0u/q2/_vector.cpp, hw2/hsjts0u/q2/_vector.hpp, hw2/hsjts0u/q2/_vector_pybind.cpp, hw2/hsjts0u/q2/_vector_test.py
=> hsjts0u-hw2-attempt1

hw2/Cycatz-nycu/q1/Makefile, hw2/Cycatz-nycu/q1/src/line.cpp, hw2/Cycatz-nycu/q2/Makefile, hw2/Cycatz-nycu/q2/src/_vector.cpp, hw2/Cycatz-nycu/q2/test_vector.py
=> [HW2] Cycatz-nycu's hw2 attempt3

proposal/Cycatz-nycu/README.org
=> [Proposal] Cycatz-nycu's proposal

proposal/YI-CHENG-SHIH645/README.rst
=> YI-CHENG-SHIH645-proposal-attempt1

proposal/eesss34690/README.rst
---
I just think up the topic for term project, while the concise method and the detailed schedule has not been decided yet. Hope there would be any advice or suggestion for the topic. Thanks!
=> eesss34690-proposal-attempt1

proposal/Cycatz-nycu/README.org
=> [Proposal] Add project link in Cycatz-nycu's proposal

proposal/crystal0523/README.md
This is my rough idea about term project, and I would like to have some idea/advice from Professor!! Any suggestion would be wonderful, thanks.
---
=> crystal0523-proposal-attempt1

proposal/eesss34690/README.rst
=> eesss34690-proposal-attempt2

proposal/Platisenic/README.md
=> [Proposal] Platisenic proposal submission2

proposal/09510/README.rst
=> [proposal]09510-proposal-attempt2

proposal/abt8601/README.rst
Sorry for the late submission. ~The mathematics part of the proposal is still missing and should be added in a couple of hours.~ **Edit:** The mathematics behind the problem has been added.
---
=> abt8601 Project Proposal: Diffusion Maps

proposal/yichi170/README.rst
---
Sorry for submitting the proposal so late. I spent too much time on finding the topic.
Although there are still lots of things need to do in proposal, I would like to have some advises from professor!
Thanks so much.
=> [Proposal] Yichi170 proposal submission

proposal/aiiuii/README.rst
=> fix commit issue

hw3/LittleLaGi/Makefile, hw3/LittleLaGi/_matrix.cpp, hw3/LittleLaGi/performance.txt, hw3/LittleLaGi/test_matrix.py
=> LittleLaGi hw3 attempt1

hw3/BoWeii/Makefile, hw3/BoWeii/_matrix.cpp, hw3/BoWeii/test_case.py
=> BoWeii-hw3-attempt1

hw3/BlueBug12/Makefile, hw3/BlueBug12/_matrix.cpp, hw3/BlueBug12/test_matrix.py
=> BlueBug12-hw3-attempt2

hw3/sam29309010/Makefile, hw3/sam29309010/_matrix.cpp, hw3/sam29309010/performance.txt, hw3/sam29309010/test_matrix.py
=> sam29309010_hw3_attempt2

hw3/secondlevel/Makefile, hw3/secondlevel/_matrix.cpp, hw3/secondlevel/_matrix.hpp, hw3/secondlevel/_matrix_pyd.cpp
=> secondlevel-hw3-attempt1

hw3/crystal0523/Makefile, hw3/crystal0523/_matrix.cpp, hw3/crystal0523/benchmark.py, hw3/crystal0523/test_matrix.py
=> crystal0523-hw3-attempt1

hw3/music87/_matrix.cpp, hw3/music87/makefile, hw3/music87/performance.txt, hw3/music87/unit_test.py
=> Music87 hw3 attempt2

hw3/music87/_matrix.cpp, hw3/music87/makefile, hw3/music87/performance.txt, hw3/music87/unit_test.py
=> Music87 hw3 attempt1

hw3/Eric860730/GEMM_test.py, hw3/Eric860730/Makefile, hw3/Eric860730/Matrix_pybind.cpp, hw3/Eric860730/benchmark.py, hw3/Eric860730/include/_GEMM.hpp, hw3/Eric860730/lib/_GEMM.cpp
=> Eric860730 hw3 attempt1

hw3/B106Roger/Makefile, hw3/B106Roger/matrix.cpp, hw3/B106Roger/performance.txt, hw3/B106Roger/performance_test.py, hw3/B106Roger/unit_test.py
=> [HW3] B106Roger hw3 attempt1

hw3/aiiuii/_matrix.cpp, hw3/aiiuii/makefile, hw3/aiiuii/unit_test.py
=> Aiiuii hw3 attempt2

hw3/Hydr8O/Makefile, hw3/Hydr8O/StopWatch.hpp, hw3/Hydr8O/_matrix.cpp, hw3/Hydr8O/check_performance.py
=> Hydr8O-hw3-secondattempt

hw3/yichi170/Makefile, hw3/yichi170/_matrix.cpp, hw3/yichi170/_matrix.hpp, hw3/yichi170/main.cpp
=> [HW3] Yichi170 hw3 attempt1

hw3/psychicalcoder/Makefile, hw3/psychicalcoder/_matrix.cpp, hw3/psychicalcoder/_matrix.h, hw3/psychicalcoder/test_matrix.py
=> [HW3] psychicalcoder's first attempt

hw3/nctu16028/Makefile, hw3/nctu16028/matrix.cpp, hw3/nctu16028/matrix.hpp, hw3/nctu16028/performance.txt, hw3/nctu16028/test_matrix.py
=> nctu16028-hw3-attempt1

hw3/Platisenic/Makefile, hw3/Platisenic/StopWatch.hpp, hw3/Platisenic/_matrix.cpp, hw3/Platisenic/_matrix.hpp, hw3/Platisenic/performance.py, hw3/Platisenic/performance.txt, hw3/Platisenic/test_matrix.py
=> Platisenic hw3 attempt1

hw3/09510/Makefile, hw3/09510/matrix.cpp, hw3/09510/test_matrix.py
=> 09510-hw3-attempt4

hw3/whtang906/Makefile, hw3/whtang906/matrix.cpp, hw3/whtang906/test_matrix.py
=> [HW3] whtang906 attempt1

hw3/anva-kn/Makefile, hw3/anva-kn/matrix.cpp, hw3/anva-kn/matrix.hpp, hw3/anva-kn/test.py
=> [hw3] anva-kn hw3

hw4/eesss34690/Makefile, hw4/eesss34690/matrix.cpp, hw4/eesss34690/test_matrix.py
=> eesss34690-hw4-attempt1

hw4/anva-kn/CustomAllocator.h, hw4/anva-kn/Makefile, hw4/anva-kn/matrix.cpp, hw4/anva-kn/matrix.hpp
---
At first there were troubles with redefinition (due to lack of knowledge of C++). After fixing that, code works.
=> [HW4] anva-kn-hw4 attempt 1

proposal/yichi170/README.rst
=> [Proposal] modify the proposal (not for sign up the presentation time)

hw4/S413/Makefile, hw4/S413/_matrix.cpp, hw4/S413/memallo.hpp
=> S413-hw4-attempt1

hw4/Hydr8O/Makefile, hw4/Hydr8O/MyAllocator.cpp, hw4/Hydr8O/StopWatch.hpp, hw4/Hydr8O/_matrix.cpp
=> Hydr8O-hw4-second-attempt

hw4/B106Roger/Makefile, hw4/B106Roger/matrix.cpp, hw4/B106Roger/performance_test.py, hw4/B106Roger/unit_test.py
=> [HW4] B106Roger attempt1

hw4/aiiuii/CustomAllocator.h, hw4/aiiuii/_matrix.cpp, hw4/aiiuii/makefile
=> aiiuii-hw4-attempt1

hw4/Platisenic/Makefile, hw4/Platisenic/_matrix.cpp, hw4/Platisenic/_matrix.hpp, hw4/Platisenic/alloc.hpp, hw4/Platisenic/test_matrix.py
=> Platisenic-hw4-attempt1

hw4/psychicalcoder/Makefile, hw4/psychicalcoder/_matrix.cpp, hw4/psychicalcoder/_matrix.h, hw4/psychicalcoder/test_matrix.py
=> [HW4] psychicalcoder's first attempt

hw4/nctu16028/Makefile, hw4/nctu16028/alloc.cpp, hw4/nctu16028/alloc.hpp, hw4/nctu16028/matrix.cpp, hw4/nctu16028/matrix.hpp
=> nctu16028-hw4-attempt1

hw4/yichi170/Makefile, hw4/yichi170/_matrix.cpp, hw4/yichi170/_matrix.hpp, hw4/yichi170/allocator.hpp, hw4/yichi170/main.cpp, hw4/yichi170/testpy.py
=> [HW4] Yichi170 hw4 attempt1

hw4/Luke2336/Makefile, hw4/Luke2336/_matrix.cpp
=> [hw4] Luke2336 1st-attempt 

hw4/hsjts0u/Makefile, hw4/hsjts0u/_matrix.cpp, hw4/hsjts0u/_matrix.hpp, hw4/hsjts0u/_matrix_pybind.cpp
=> [HW4] hsjts0u-hw4-attempt1

hw4/Cycatz-nycu/Makefile, hw4/Cycatz-nycu/matrix.cpp, hw4/Cycatz-nycu/matrix.h
=> [HW4] Cycatz-nycu's 1st-attempt 

hw4/BlueBug12/Makefile, hw4/BlueBug12/_matrix.cpp
=> BlueBug12-hw4-attempt1

hw4/sam29309010/Makefile, hw4/sam29309010/_matrix.cpp, hw4/sam29309010/test_matrix.py
=> sam29309010_hw4_attempt1

hw4/secondlevel/Allocator.hpp, hw4/secondlevel/Makefile, hw4/secondlevel/_matrix.cpp
=> Secondlevel-hw4-attempt1

hw4/LittleLaGi/Makefile, hw4/LittleLaGi/MyAllocator.hpp, hw4/LittleLaGi/_matrix.cpp
=> LittleLaGi-hw4-attempt1

hw4/YI-CHENG-SHIH645/Makefile, hw4/YI-CHENG-SHIH645/matrix.cpp
=> YI-CHENG-SHIH645-hw4-attempt1

hw4/chrisPyr/Makefile, hw4/chrisPyr/include/Allocator.hpp, hw4/chrisPyr/include/Mat.hpp, hw4/chrisPyr/lib/Mat.cpp, hw4/validate.py
=> [HW4] chrisPyr hw4 submission

hw4/abt8601/.clang-format, hw4/abt8601/Makefile, hw4/abt8601/allocator.cpp, hw4/abt8601/allocator.hpp, hw4/abt8601/benchmark.py, hw4/abt8601/benchmark.sh, hw4/abt8601/matrix.hpp, hw4/abt8601/matrix_mul.cpp, hw4/abt8601/matrix_mul.hpp, hw4/abt8601/matrix_pybind.cpp, hw4/abt8601/performance.txt, hw4/abt8601/test_matrix.py, hw4/abt8601/test_matrix_alloc.py
=> abt8601 HW4 Attempt 1

hw4/whtang906/CustomAllocator.h, hw4/whtang906/makefile, hw4/whtang906/matrix.cpp
=> [HW4] whtang906 attempt1

hw4/crystal0523/Makefile, hw4/crystal0523/MyAllocater.cpp, hw4/crystal0523/MyAllocator.cpp, hw4/crystal0523/_matrix.cpp
=> crystal0523-hw4-attempt1

hw4/09510/Makefile, hw4/09510/matrix.cpp
=> 09510-hw4-attempt1

proposal/README.rst
=> [presentation] BlueBug12 sigin up for presentation time slot

proposal/README.rst
=> [presentation] 09510 sign up for presentation

proposal/README.rst
=> [presentation] eesss34690 sign up for presentation

proposal/README.rst
=>   [presentation] Cycatz sign up for presentation

proposal/README.rst
=> [presentation] nctu16028 sign up for presentation

proposal/README.rst
=> [presentation] psychicalcoder's sign-up for presentation

proposal/README.rst
=> [presentation] Yichi170 sign up for presentation

proposal/README.rst
=> [presentation] Platisenic sign up for presentation

proposal/README.rst
=> [presentation] chrisPyr sign up for time slot C1

proposal/README.rst
=> [presentation] hsjts0u sign up for slot C8

proposal/README.rst
=> [Presentation] Eric860730 Sign up for time slot C9

proposal/README.rst
=> [presentation] BoWeii sign up for  B4

proposal/README.rst
=> [presentation]S413_Reservation_B7

proposal/README.rst
=> [presentation] LittleLaGI signs up for B5

proposal/README.rst
=> [presentation] crysatl0523 resigned up for time slot

proposal/README.rst
=> B106Roger proposal sign up

proposal/README.rst
=> [presentation] secondlevel signs up for A8

proposal/README.rst
=> sam29309010 proposal sign up for presentation

proposal/sam29309010/readme.md
=> sam29309010 modify proposal (repository added)

proposal/README.rst
=> [presentation] music87 sign up for A5

proposal/README.rst
=> [presentation] whtang906 sign up for presentation

proposal/Hydr8O/README.rst, proposal/README.rst
=> [presentation]Hydr8O Presentation sign up A4

hw5/abt8601/.clang-format, hw5/abt8601/Makefile, hw5/abt8601/benchmark.py, hw5/abt8601/benchmark.sh, hw5/abt8601/matrix.hpp, hw5/abt8601/matrix_mul.cpp, hw5/abt8601/performance.txt, hw5/abt8601/test_matrix.py
=> abt8601 HW5 Attempt 1

hw5/music87/makefile, hw5/music87/matrix.hpp
=> Music87 hw5 attempt2

hw5/music87/makefile, hw5/music87/matrix.hpp
=> Music87 hw5 attempt1

hw5/crystal0523/Makefile, hw5/crystal0523/matrix.hpp
=> crystal0523-hw5-attempt1

hw5/S413/Makefile, hw5/S413/matrix.hpp
=> S413_Hw5_Attempt1

hw5/Hydr8O/Makefile, hw5/Hydr8O/matrix.hpp, hw5/Hydr8O/mod.cpp
=> Hydr8O-hw5-first try

hw5/Eric860730/Makefile, hw5/Eric860730/matrix.hpp
=> [HW5] Eric860730 attempt hw5.

hw5/Platisenic/Makefile, hw5/Platisenic/matrix.hpp, hw5/Platisenic/mod.cpp, hw5/Platisenic/test_matrix.py
=> Platisenic hw5 attempt1

hw5/psychicalcoder/Makefile, hw5/psychicalcoder/matrix.cpp, hw5/psychicalcoder/matrix.hpp, hw5/psychicalcoder/mod.cpp, hw5/psychicalcoder/test_matrix.py
=> [HW5] psychicalcoder's first attempt

hw5/nctu16028/Makefile, hw5/nctu16028/matrix.cpp, hw5/nctu16028/matrix.hpp
=> nctu16028-hw5-attempt1

hw5/yichi170/Makefile, hw5/yichi170/matrix.hpp
=> [HW5] yichi170-hw5-attempt1

hw5/Luke2336/Makefile, hw5/Luke2336/matrix.hpp
=> [hw5] Luke2336 1st-attempt

hw5/hsjts0u/Makefile, hw5/hsjts0u/matrix.hpp
=> [HW5]hsjts0u-hw5-attempt1

hw5/Cycatz-nycu/Makefile, hw5/Cycatz-nycu/matrix.cpp, hw5/Cycatz-nycu/matrix.hpp, hw5/Cycatz-nycu/test_matrix.py
=> [HW5] Cycatz-nycu's 1st-attempt

hw5/BlueBug12/Makefile, hw5/BlueBug12/matrix.hpp
=> BlueBug12 hw5 attempt1

hw5/sam29309010/Makefile, hw5/sam29309010/matrix.hpp
=> sam29309010_hw5_attempt3

hw5/secondlevel/Makefile, hw5/secondlevel/matrix.hpp
=> Secondlevel-hw5-attempt3

hw5/secondlevel/Makefile, hw5/secondlevel/matrix.hpp
=> Secondlevel-hw5-attempt1

hw5/secondlevel/Makefile, hw5/secondlevel/matrix.hpp
=> Secondlevel-hw5-attempt2

hw5/LittleLaGi/Makefile, hw5/LittleLaGi/matrix.hpp
=> [HW5] LittleLaGi attempt1

hw5/YI-CHENG-SHIH645/Makefile, hw5/YI-CHENG-SHIH645/matrix.cpp, hw5/YI-CHENG-SHIH645/matrix.hpp
=> YI-CHENG-SHIH645-hw5-attempt1

hw5/BoWeii/Makefile, hw5/BoWeii/matrix.hpp
=> Boweii hw5 attempt1

hw6/sam29309010/Makefile, hw6/sam29309010/_matrix.cpp
=> sam29309010_hw6_attempt1

hw6/Hydr8O/Makefile, hw6/Hydr8O/_matrix.cpp
=> Hydr8O-hw6-second-try

hw6/Platisenic/Makefile, hw6/Platisenic/matrix.cpp, hw6/Platisenic/test_matrix.py
=> Platisenic hw6 attempt1

hw6/psychicalcoder/Makefile, hw6/psychicalcoder/matrix.cpp, hw6/psychicalcoder/matrix.hpp, hw6/psychicalcoder/mod.cpp, hw6/psychicalcoder/test_matrix.py
=> [HW6] psychicalcoder's first attempt

hw6/nctu16028/Makefile, hw6/nctu16028/matrix.cpp, hw6/nctu16028/matrix.hpp
=> nctu16028-hw6-attempt1

hw6/yichi170/Makefile, hw6/yichi170/main.cpp, hw6/yichi170/matrix.hpp
=> [HW6] Yichi170 hw6 attempt1

hw6/Luke2336/Makefile, hw6/Luke2336/_matrix.cpp
=> [hw6] Luke2336's 1st attempt

hw6/hsjts0u/Makefile, hw6/hsjts0u/matrix.hpp, hw6/hsjts0u/matrix_pybind.cpp
=> [HW6] hsjts0u-hw6-attempt1

hw6/Cycatz-nycu/Makefile, hw6/Cycatz-nycu/matrix.cpp, hw6/Cycatz-nycu/matrix.hpp, hw6/Cycatz-nycu/mod.cpp, hw6/Cycatz-nycu/test_matrix.py
=> [HW6] Cycatz-nycu's 1st-attempt

hw6/BlueBug12/Makefile, hw6/BlueBug12/_matrix.cpp
=> BlueBug12 hw6 attempt2

hw6/secondlevel/Makefile, hw6/secondlevel/_matrix.cpp
=> Secondlevel-hw6-attempt1

hw6/LittleLaGi/Makefile, hw6/LittleLaGi/matrix.hpp, hw6/LittleLaGi/pybind.cpp
=> LittleLaGi-hw6-attempt1

hw6/chrisPyr/Makefile, hw6/chrisPyr/include/Mat.hpp, hw6/chrisPyr/lib/Mat.cpp
=> [HW6] chrisPyr hw6 submission

hw6/crystal0523/Makefile, hw6/crystal0523/_matrix.cpp
=> crystal0523-hw6-attempt1

hw6/whtang906/makefile, hw6/whtang906/matrix.cpp
=> [HW6] whtang906 attempt 1

hw6/BoWeii/Makefile, hw6/BoWeii/_matrix.cpp
=> BoWeii-hw6-attempt1

hw6/abt8601/.clang-format, hw6/abt8601/Makefile, hw6/abt8601/matrix.hpp, hw6/abt8601/matrix_mul.cpp, hw6/abt8601/matrix_mul.hpp, hw6/abt8601/matrix_pybind.cpp, hw6/abt8601/test_matrix.py
=> abt8601 HW6 Attempt 1

hw6/music87/_matrix.cpp, hw6/music87/makefile, hw6/music87/matrix.hpp
=> Music87 hw6 attempt1

hw6/S413/Makefile, hw6/S413/_matrix.cpp
=> S413-Hw6-Attempt1
